/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Empleado;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author iris
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    Empleado empleado;
    
    
    public Administrador() {
       
        initComponents();
        this.setSize(1200,700);
        this.setLocationRelativeTo(null);
        
        
        //hora y fecha
        Date sistemaFech = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd MMMM yyyy");
        fecha.setText(formato.format(sistemaFech));
        //Hora del sistema
        Timer tiempo = new Timer(100, new Administrador.horas());
        tiempo.start();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsuario = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        btDesconectar = new javax.swing.JButton();
        btClientes = new javax.swing.JButton();
        btProveedores = new javax.swing.JButton();
        btEmpleados = new javax.swing.JButton();
        btProductos = new javax.swing.JButton();
        btRegistroVentas = new javax.swing.JButton();
        btConfiguracion = new javax.swing.JButton();
        btGastos = new javax.swing.JButton();
        btReportes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        lbUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(lbUsuario);
        lbUsuario.setBounds(140, 80, 150, 50);

        hora.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        hora.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(hora);
        hora.setBounds(860, 552, 310, 30);

        fecha.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(fecha);
        fecha.setBounds(860, 610, 280, 40);

        btDesconectar.setBackground(new java.awt.Color(255, 51, 51));
        btDesconectar.setBorder(null);
        btDesconectar.setContentAreaFilled(false);
        btDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(btDesconectar);
        btDesconectar.setBounds(20, 170, 260, 80);

        btClientes.setBackground(new java.awt.Color(255, 255, 255));
        btClientes.setBorder(null);
        btClientes.setContentAreaFilled(false);
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btClientes);
        btClientes.setBounds(940, 50, 170, 170);

        btProveedores.setBackground(new java.awt.Color(255, 255, 255));
        btProveedores.setBorder(null);
        btProveedores.setContentAreaFilled(false);
        btProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btProveedores);
        btProveedores.setBounds(370, 280, 170, 170);

        btEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btEmpleados.setBorder(null);
        btEmpleados.setContentAreaFilled(false);
        btEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btEmpleados);
        btEmpleados.setBounds(370, 50, 170, 170);

        btProductos.setBackground(new java.awt.Color(255, 255, 255));
        btProductos.setBorder(null);
        btProductos.setContentAreaFilled(false);
        btProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btProductos);
        btProductos.setBounds(560, 50, 170, 170);

        btRegistroVentas.setBackground(new java.awt.Color(255, 255, 255));
        btRegistroVentas.setBorder(null);
        btRegistroVentas.setContentAreaFilled(false);
        btRegistroVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistroVentas);
        btRegistroVentas.setBounds(750, 50, 170, 170);

        btConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        btConfiguracion.setBorder(null);
        btConfiguracion.setContentAreaFilled(false);
        btConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(btConfiguracion);
        btConfiguracion.setBounds(940, 280, 170, 170);

        btGastos.setBackground(new java.awt.Color(255, 255, 255));
        btGastos.setBorder(null);
        btGastos.setContentAreaFilled(false);
        btGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGastosActionPerformed(evt);
            }
        });
        getContentPane().add(btGastos);
        btGastos.setBounds(750, 280, 170, 170);

        btReportes.setBackground(new java.awt.Color(255, 255, 255));
        btReportes.setBorder(null);
        btReportes.setContentAreaFilled(false);
        getContentPane().add(btReportes);
        btReportes.setBounds(560, 280, 170, 170);

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 270, 260, 80);

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 380, 260, 80);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/interfazAdmin.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1210, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesconectarActionPerformed
       if (JOptionPane.showConfirmDialog(null, "¿Esta segur@ de salir?", "WARNING",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            //opcion de la caja
            this.dispose();
            new login().setVisible(true);}
    }//GEN-LAST:event_btDesconectarActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
  
        new vistaClientes(this, true).setVisible(true);
        
    }//GEN-LAST:event_btClientesActionPerformed

    private void btProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductosActionPerformed
        new vistaProductos(this, true).setVisible(true);
        
    }//GEN-LAST:event_btProductosActionPerformed

    private void btEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmpleadosActionPerformed
        new vistaEmpleados(this, true).setVisible(true);
        
    }//GEN-LAST:event_btEmpleadosActionPerformed

    private void btProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProveedoresActionPerformed
        new vistaProveedores(this, true).setVisible(true);
    }//GEN-LAST:event_btProveedoresActionPerformed

    private void btGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGastosActionPerformed
        new vistaGastos(this, true).setVisible(true);
    }//GEN-LAST:event_btGastosActionPerformed

    private void btConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguracionActionPerformed
       new vistaCaja(this, true).setVisible(true);
    }//GEN-LAST:event_btConfiguracionActionPerformed

    private void btRegistroVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroVentasActionPerformed
        new vistaVentas(this, true).setVisible(true);
    }//GEN-LAST:event_btRegistroVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }
    
    class horas implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Date sistemaHora = new Date();
            String pmAm = "hh:mm:ss a";
            SimpleDateFormat formato = new SimpleDateFormat(pmAm);
            Calendar now = Calendar.getInstance();
            hora.setText(String.format(formato.format(sistemaHora), now));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btConfiguracion;
    private javax.swing.JButton btDesconectar;
    private javax.swing.JButton btEmpleados;
    private javax.swing.JButton btGastos;
    private javax.swing.JButton btProductos;
    private javax.swing.JButton btProveedores;
    private javax.swing.JButton btRegistroVentas;
    private javax.swing.JButton btReportes;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbUsuario;
    // End of variables declaration//GEN-END:variables
}
