/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.ClienteJpaController;
import Entidades.Cliente;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author irisa
 */
public class editarCliente extends javax.swing.JDialog {

    ClienteJpaController controladorCliente;
    /**
     * Creates new form nuevoCliente
     */
    public editarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(420,450);
        this.setLocationRelativeTo(null);
        controladorCliente = new ClienteJpaController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nitCliente = new javax.swing.JTextField();
        nombreCliente = new javax.swing.JTextField();
        dirCliente = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(nitCliente);
        nitCliente.setBounds(50, 119, 320, 35);
        getContentPane().add(nombreCliente);
        nombreCliente.setBounds(50, 211, 320, 35);
        getContentPane().add(dirCliente);
        dirCliente.setBounds(50, 306, 320, 35);

        btGuardar.setBorder(null);
        btGuardar.setContentAreaFilled(false);
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(230, 370, 150, 40);

        btCancelar.setBorder(null);
        btCancelar.setContentAreaFilled(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar);
        btCancelar.setBounds(40, 370, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nuevoCliente.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        nitCliente.setText("");
        nombreCliente.setText("");
        dirCliente.setText("");
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        guardarNuevoCliente();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void guardarNuevoCliente(){
    
        try {
            Cliente cli = new Cliente();
            
            cli.setNitCliente(nitCliente.getText());
            cli.setNombreCliente(nombreCliente.getText());
            cli.setDireccion(dirCliente.getText());
            
            controladorCliente.create(cli);
            
            JOptionPane.showMessageDialog(null, "Cliente guardado exitosamente");
            
        nitCliente.setText("");
        nombreCliente.setText("");
        dirCliente.setText("");
            
        } catch (Exception ex) {
            Logger.getLogger(editarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                editarCliente dialog = new editarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JTextField dirCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nitCliente;
    private javax.swing.JTextField nombreCliente;
    // End of variables declaration//GEN-END:variables
}
