/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.CajaJpaController;
import Entidades.Caja;
import Entidades.Empleado;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author irisa
 */
public class movimientoCaja extends javax.swing.JDialog {

    /**
     * Creates new form movimientoCaja
     */
    Empleado empleado;
    CajaJpaController controladorCaja;
    Date date;
    public movimientoCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        empleado = new Empleado();
        controladorCaja = new CajaJpaController();
        date = new Date();
        this.setSize(420,450);
        this.setLocationRelativeTo(null);
    }
    
    public void setEmpleado(Empleado emp){
    
         //hora y fecha
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        hora.setText(hourFormat.format(date));
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        fecha.setText(dateFormat.format(date));
        
        empleado = emp;
        nomEmpleado.setText(emp.getNombreEmpleado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomEmpleado = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        monto = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        nomEmpleado.setEditable(false);
        nomEmpleado.setBorder(null);
        getContentPane().add(nomEmpleado);
        nomEmpleado.setBounds(208, 52, 163, 35);

        fecha.setEditable(false);
        fecha.setBorder(null);
        getContentPane().add(fecha);
        fecha.setBounds(208, 123, 163, 35);

        hora.setEditable(false);
        hora.setBorder(null);
        getContentPane().add(hora);
        hora.setBounds(208, 195, 163, 35);

        monto.setBorder(null);
        getContentPane().add(monto);
        monto.setBounds(208, 272, 163, 35);

        btGuardar.setContentAreaFilled(false);
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(220, 350, 160, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/caja.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        
        Caja caj = new Caja();

        try {
        caj.setIdEmpleado(empleado);
        caj.setFecha(date);
        caj.setHora(date);
        caj.setMonto(Double.parseDouble(monto.getText()));
            controladorCaja.create(caj);
            JOptionPane.showMessageDialog(null, "Guardado exitosamente");
        } catch (Exception ex) {
            Logger.getLogger(movimientoCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
    }//GEN-LAST:event_btGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movimientoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movimientoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movimientoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movimientoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                movimientoCaja dialog = new movimientoCaja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField nomEmpleado;
    // End of variables declaration//GEN-END:variables
}
