/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BD.Consultas;
import BD.exceptions.NonexistentEntityException;
import Controladores.ClienteJpaController;
import Controladores.DetallefacturaJpaController;
import Controladores.EmpleadoJpaController;
import Controladores.FacturaJpaController;
import Controladores.ProductoJpaController;
import Entidades.Cliente;
import Entidades.Detallefactura;
import Entidades.DetallefacturaPK;
import Entidades.Empleado;
import Entidades.Factura;
import Entidades.Producto;
import Entidades.Producto_;
import Entidades.datosTabla;
import com.sun.imageio.plugins.jpeg.JPEG;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iris
 */
public class NuevaVenta extends javax.swing.JDialog {

    /**
     * Creates new form NuevaVenta
     * @param parent
     * @param modal
     */
    java.awt.Frame padre;
    Empleado empleado;
    Cliente cliente;
    Producto producto;
    ProductoJpaController controlProductos = new ProductoJpaController();
    Producto prd;
    String columnas[]={"Codigo","Producto","Precio","Cantidad","SubTotal"};
    List <datosTabla> agregados = new ArrayList<>();
    //datosTabla nuevoProducto=new datosTabla();
    DefaultTableModel modelo = new DefaultTableModel();
    BigDecimal total=new BigDecimal(0);
    Date sistemaFech = new Date();
    
    public NuevaVenta(java.awt.Frame parent, boolean modal,Empleado emp) { 
        super(parent, modal);
        
        initComponents();
        this.setSize(1200, 750);
        padre=parent;
        this.empleado=emp;
       if(empleado==null){
            vendedorDefault();
       }
        
        tabla.setModel(modelo);
        
        for (int i = 0; i < columnas.length; i++) {
        modelo.addColumn(columnas[i]);
        }
        
        nomEmpleado.setText(empleado.getNombreEmpleado());
        
        SimpleDateFormat formato = new SimpleDateFormat("dd MMMM yyyy");
        fecha.setText(formato.format(sistemaFech));
        //Hora del sistema
       // Timer tiempo = new Timer(100, new menuPrincipal.horas());
        //tiempo.start();
    }
    
    public void vendedorDefault(){
        EmpleadoJpaController empleados = new EmpleadoJpaController();
        empleado=empleados.findEmpleado(123);
        if(empleado==null){
            System.out.println("visual.NuevaVenta.vendedorDefault()");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTotal = new javax.swing.JLabel();
        lbNumFactura = new javax.swing.JLabel();
        nomEmpleado = new javax.swing.JLabel();
        jtNitCliente = new javax.swing.JFormattedTextField();
        jtCodigo = new javax.swing.JFormattedTextField();
        btAgregar = new javax.swing.JButton();
        fecha = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        nombCliente = new javax.swing.JTextField();
        direCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btCobrar = new javax.swing.JButton();
        btVerPrecio = new javax.swing.JButton();
        btCancelarCompra = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        lbTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbTotal);
        lbTotal.setBounds(940, 590, 190, 40);

        lbNumFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNumFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbNumFactura);
        lbNumFactura.setBounds(900, 130, 230, 20);

        nomEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nomEmpleado);
        nomEmpleado.setBounds(880, 70, 270, 20);

        jtNitCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNitClienteFocusLost(evt);
            }
        });
        jtNitCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNitClienteKeyPressed(evt);
            }
        });
        getContentPane().add(jtNitCliente);
        jtNitCliente.setBounds(270, 50, 240, 30);

        jtCodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCodigoFocusLost(evt);
            }
        });
        jtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(jtCodigo);
        jtCodigo.setBounds(320, 150, 260, 30);

        btAgregar.setBackground(new java.awt.Color(0, 204, 51));
        btAgregar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btAgregar.setText("+");
        btAgregar.setBorder(null);
        btAgregar.setOpaque(false);
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregar);
        btAgregar.setBounds(770, 150, 50, 30);
        getContentPane().add(fecha);
        fecha.setBounds(1000, 160, 160, 30);

        cantidad.setEditable(false);
        cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidadFocusLost(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadKeyPressed(evt);
            }
        });
        getContentPane().add(cantidad);
        cantidad.setBounds(720, 150, 40, 30);

        nombCliente.setEditable(false);
        nombCliente.setBackground(new java.awt.Color(255, 255, 255));
        nombCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nombCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombClienteFocusLost(evt);
            }
        });
        getContentPane().add(nombCliente);
        nombCliente.setBounds(630, 50, 190, 30);

        direCliente.setEditable(false);
        direCliente.setBackground(new java.awt.Color(255, 255, 255));
        direCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                direClienteFocusLost(evt);
            }
        });
        getContentPane().add(direCliente);
        direCliente.setBounds(360, 100, 460, 30);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Producto", "Precio", "Cantidad", "Importe"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 230, 1040, 310);

        btCobrar.setBackground(new java.awt.Color(204, 204, 204));
        btCobrar.setBorder(null);
        btCobrar.setContentAreaFilled(false);
        btCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCobrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCobrar);
        btCobrar.setBounds(540, 580, 250, 100);

        btVerPrecio.setBackground(new java.awt.Color(204, 204, 204));
        btVerPrecio.setBorder(null);
        btVerPrecio.setContentAreaFilled(false);
        btVerPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(btVerPrecio);
        btVerPrecio.setBounds(270, 580, 250, 100);

        btCancelarCompra.setBackground(new java.awt.Color(204, 204, 204));
        btCancelarCompra.setBorder(null);
        btCancelarCompra.setContentAreaFilled(false);
        btCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelarCompra);
        btCancelarCompra.setBounds(60, 575, 180, 50);

        btSalir.setBackground(new java.awt.Color(204, 204, 204));
        btSalir.setBorder(null);
        btSalir.setContentAreaFilled(false);
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(60, 635, 180, 50);

        imagen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nuevaVenta.png"))); // NOI18N
        getContentPane().add(imagen);
        imagen.setBounds(0, 0, 1200, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
       
        volver();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarCompraActionPerformed
        volver();        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarCompraActionPerformed

    private void jtNitClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNitClienteFocusLost
        
        
    }//GEN-LAST:event_jtNitClienteFocusLost

    private void nombClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombClienteFocusLost
        
    }//GEN-LAST:event_nombClienteFocusLost

    private void direClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direClienteFocusLost
       
    }//GEN-LAST:event_direClienteFocusLost

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
       int cantidadProducto = Integer.parseInt(cantidad.getText());
        agregar(cantidadProducto);
       jtCodigo.requestFocus();
        
    }//GEN-LAST:event_btAgregarActionPerformed

    public void agregar(int cantidadProducto){
     // TODO add your handling code here:
        try{
            //int cantidadProducto = Integer.parseInt(cantidad.getText());
            BigDecimal subTot;
        String valores[] = new String[columnas.length];
          if(producto.getStock()<cantidadProducto){
           JOptionPane.showMessageDialog(null, "Cantidad sobrepasa el stock","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                          
              valores[0]=producto.getCodigoBarras();
              valores[1]=producto.getNombreProducto();
              valores[2]=String.valueOf(producto.getPrecioProducto());
              valores[3]=cantidad.getText();
              subTot=(producto.getPrecioProducto().multiply(new BigDecimal( cantidadProducto)));
              valores[4]=String.valueOf(subTot);
              
              datosTabla nuevoProducto=new datosTabla();
              
              nuevoProducto.setCantidad(Integer.parseInt(cantidad.getText()));
              nuevoProducto.setProducto(producto);
              nuevoProducto.setSubTotal(subTot);
              agregados.add(nuevoProducto);
              
              modelo.addRow(valores);
              total=total.add(subTot);
              System.out.println("total: "+total);
              lbTotal.setText(String.valueOf("Q "+total));
              jtCodigo.setText("");
              cantidad.setText("");
              
              valores=null;
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad correcta","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void jtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCodigoFocusLost
       //buscarPorCodigo();
       
    }//GEN-LAST:event_jtCodigoFocusLost

    public void agregarRepetidos(int cantidadProducto, Producto prod){
     // TODO add your handling code here:
        try{
            //int cantidadProducto = Integer.parseInt(cantidad.getText());
            BigDecimal subTot;
            String valores[] = new String[columnas.length];
          if(prod.getStock()<cantidadProducto){
           JOptionPane.showMessageDialog(null, "Cantidad sobrepasa el stock","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                          
              valores[0]=prod.getCodigoBarras();
              valores[1]=prod.getNombreProducto();
              valores[2]=String.valueOf(prod.getPrecioProducto());
              valores[3]=String.valueOf(cantidadProducto);
              subTot=(prod.getPrecioProducto().multiply(new BigDecimal( cantidadProducto)));
              valores[4]=String.valueOf(subTot);
              
              datosTabla nuevoProducto=new datosTabla();
              
              nuevoProducto.setCantidad(cantidadProducto);
              nuevoProducto.setProducto(prod);
              nuevoProducto.setSubTotal(subTot);
              agregados.add(nuevoProducto);
              
              modelo.addRow(valores);
              total=total.add(subTot);
              System.out.println("total: "+total);
              lbTotal.setText(String.valueOf("Q "+total));
              jtCodigo.setText("");
              cantidad.setText("");
              
              valores=null;
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad correcta","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void buscarPorCodigo(){
    
         producto= new Consultas().buscarCodigoBarras(jtCodigo.getText());
        if(producto==null){
            JOptionPane.showMessageDialog(null, "El producto no existe","Error",JOptionPane.ERROR_MESSAGE);
        }else{            
            cantidad.setEditable(true);
 
        }
    }
    private void cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cantidadFocusLost

    private void jtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCodigoFocusGained
        // TODO add your handling code here:
        cantidad.setEditable(false);
        producto=null;
    }//GEN-LAST:event_jtCodigoFocusGained

    private void btVerPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerPrecioActionPerformed
        
    }//GEN-LAST:event_btVerPrecioActionPerformed

    private void btCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCobrarActionPerformed
        // TODO add your handling code here:
       BigDecimal descuento =  new BigDecimal(JOptionPane.showInputDialog("Ingrese descuento"));
       FacturaJpaController facturas = new FacturaJpaController();
       int numFactura=facturas.getFacturaCount();
       System.out.println("Ultima Factura: "+numFactura);
       numFactura++;
       
        Factura factura = new Factura();
        Cliente buscar;
        
        factura.setIdEmpleado(empleado);
        cliente.setNitCliente(jtNitCliente.getText());
        cliente.setDireccion(direCliente.getText());
        cliente.setNombreCliente(nombCliente.getText());
        buscar=new ClienteJpaController().findCliente(cliente.getNitCliente());
        if(buscar==null){
           try {
               //new ClienteJpaController().create(cliente);
               //new nuevoCliente(this, false).setVisible(true);
           } catch (Exception ex) {
               Logger.getLogger(NuevaVenta.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        factura.setNitCliente(cliente);
        factura.setNumFactura(numFactura);
        factura.setFecha(sistemaFech);
        factura.setHora(sistemaFech);
        //descuento
        BigDecimal nuevoTotal = total.subtract(descuento);
        factura.setTotalVenta(nuevoTotal);//total venta
        try {
            facturas.create(factura);   
            ingresarDetalles(numFactura);
            this.dispose();
            new cobrar(padre, true,nuevoTotal).setVisible(true);
        } catch (Exception ex) {
            System.err.println("Error al ingresar factura");
            Logger.getLogger(NuevaVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btCobrarActionPerformed

    private void jtNitClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNitClienteKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarPorNit(); 
            jtCodigo.requestFocus();
            }
    }//GEN-LAST:event_jtNitClienteKeyPressed

    private void jtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCodigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            buscarPorCodigo();
            cantidad.requestFocus();
            }
    }//GEN-LAST:event_jtCodigoKeyPressed

    private void cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
           int cantidadProducto = Integer.parseInt(cantidad.getText());
            agregar(cantidadProducto);
            jtCodigo.requestFocus();
            }
        
    }//GEN-LAST:event_cantidadKeyPressed
public void ingresarDetalles(int numFactura){
    
        DetallefacturaJpaController detalles = new DetallefacturaJpaController();
        Detallefactura detalle = new Detallefactura();
        DetallefacturaPK pk =  new DetallefacturaPK();
        Consultas actualizacion =  new Consultas();

        pk.setNumFactura(numFactura);
        ProductoJpaController productos = new ProductoJpaController();
        int resta;
        
       for(int i=0;i<agregados.size();i++){
        pk.setIdDetalle(i);     
        detalle.setDetalleFacturaPK(pk);
        detalle.setCantidad(agregados.get(i).getCantidad());
        detalle.setPrecio(agregados.get(i).getSubTotal());
        detalle.setIdProducto(agregados.get(i).getProducto()); 
        
        
           try {
             detalles.create(detalle);  
            actualizacion.restarStock(detalle.getCantidad(), detalle.getIdProducto().getIdProducto());
               System.out.println("Detalle insertado: "+i);
           } catch (Exception e) {
               System.out.println("detalle "+i+": "+e.getMessage());
           }
           
            
                
                //agregados.get(i).getProducto());
           
           
        
}
        System.err.println("ingresado exitosamente");
}

public void buscarPorNit(){

     ClienteJpaController clientes = new ClienteJpaController();
        String nitCliente="0";
        try{
            if(jtNitCliente.getText().equals("")){
                nitCliente="CF";
            }else{
                nitCliente=jtNitCliente.getText();
            }
             
            cliente=clientes.findCliente(nitCliente);
            if(cliente==null){
                
                new nuevoCliente(this, false).setVisible(true);
                /*nombCliente.setEditable(true);
                direCliente.setEditable(true);*/
                
            }else{
                nombCliente.setText(cliente.getNombreCliente());
                direCliente.setText(cliente.getDireccion());
                jtNitCliente.setEditable(false);
            }
            
        }catch(Exception e){
            System.out.println("Error en visual.NuevaVenta.jtNitClienteFocusLost()");
        }
}


    /**
     * @param args the command line arguments
     */
    
    public void volver(){
        
       padre.setVisible(true);
       this.dispose();
    }
   
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevaVenta dialog = new NuevaVenta(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btCancelarCompra;
    private javax.swing.JButton btCobrar;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btVerPrecio;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField direCliente;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel imagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jtCodigo;
    private javax.swing.JFormattedTextField jtNitCliente;
    private javax.swing.JLabel lbNumFactura;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel nomEmpleado;
    private javax.swing.JTextField nombCliente;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
