/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BD.Consultas;
import Controladores.ProductoJpaController;
import Controladores.ProveedorJpaController;
import Entidades.Producto;
import Entidades.Proveedor;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author irisa
 */
public class nuevoProducto extends javax.swing.JDialog {

    ProveedorJpaController controladorProveedor = new ProveedorJpaController();
    ProductoJpaController controladorProducto = new ProductoJpaController();
    Proveedor prov;
    Producto producto;

    public nuevoProducto(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Llenar_JCombobox();
        this.setSize(420, 450);
        this.setLocationRelativeTo(null);
        prov = new Proveedor();
    }
    
     DefaultComboBoxModel dc = new DefaultComboBoxModel();
    private void Llenar_JCombobox(){
        jComboBox1.setModel(dc);
        List<Proveedor>listaProveedores;
        listaProveedores=controladorProveedor.findProveedorEntities();
        for (int i = 0; i < listaProveedores.size(); i++) {
           dc.addElement(listaProveedores.get(i).getNombreProveedor());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        codigoBarras = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 390, 150, 40);

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 390, 150, 40);

        codigoBarras.setBorder(null);
        codigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoBarrasKeyPressed(evt);
            }
        });
        getContentPane().add(codigoBarras);
        codigoBarras.setBounds(50, 118, 320, 25);

        nombre.setBorder(null);
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });
        getContentPane().add(nombre);
        nombre.setBounds(50, 193, 320, 25);

        precio.setBorder(null);
        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioKeyPressed(evt);
            }
        });
        getContentPane().add(precio);
        precio.setBounds(50, 263, 160, 25);

        stock.setBorder(null);
        stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stockKeyPressed(evt);
            }
        });
        getContentPane().add(stock);
        stock.setBounds(240, 263, 130, 25);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(50, 338, 320, 25);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(383, 0, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nuevoProducto.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        codigoBarras.setText("");
        nombre.setText("");
        precio.setText("");
        stock.setText("");
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void codigoBarrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoBarrasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            nombre.requestFocus();
            }
    }//GEN-LAST:event_codigoBarrasKeyPressed

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            precio.requestFocus();
            }
    }//GEN-LAST:event_nombreKeyPressed

    private void precioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            stock.requestFocus();
            }
    }//GEN-LAST:event_precioKeyPressed

    private void stockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            jComboBox1.requestFocus();
            }
    }//GEN-LAST:event_stockKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardarProducto();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarPorCodigo(){
    
         producto= new Consultas().buscarCodigoBarras(codigoBarras.getText());
        if(producto!=null){
           
            JOptionPane.showMessageDialog(null, "Producto ya existente");
            codigoBarras.setText("");
            codigoBarras.requestFocus();
            
        }else{
            
            
        }
    }
    private void guardarProducto(){
    
       Producto prod = new Producto();
       try{
            BigDecimal price = new BigDecimal(precio.getText());
       
       prod.setNombreProducto(nombre.getText());
       prod.setPrecioProducto(price);
       prod.setCodigoBarras(codigoBarras.getText());
       prod.setStock(Integer.parseInt(stock.getText()));
       
       int s = jComboBox1.getSelectedIndex();
       System.out.println(s);
       prov = controladorProveedor.findProveedor(s+1);
       System.out.println(prov);
       prod.setProveedor(prov);
       
       controladorProducto.create(prod);
       
       JOptionPane.showMessageDialog(null, "Producto guardado exitosamente");
       
       nombre.setText("");
       precio.setText("");
       codigoBarras.setText("");
       stock.setText("");
       jComboBox1.setSelectedIndex(0);
       
       }
       catch(Exception e){}
       
      
       
       
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nuevoProducto dialog = new nuevoProducto(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoBarras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
