/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.EmpleadoJpaController;
import Entidades.Empleado;
import Entidades.Empleado_;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author irisa
 */
public class nuevoEmpleado extends javax.swing.JDialog {

    /**
     * Creates new form nuevoEmpleado
     */
    EmpleadoJpaController controladorEmpleado;
    public nuevoEmpleado(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(420,450);
        this.setLocationRelativeTo(null);
        controladorEmpleado = new EmpleadoJpaController();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idEmp = new javax.swing.JTextField();
        nomEmp = new javax.swing.JTextField();
        apEmp = new javax.swing.JTextField();
        contraEmp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        idEmp.setBorder(null);
        getContentPane().add(idEmp);
        idEmp.setBounds(50, 118, 320, 25);

        nomEmp.setBorder(null);
        getContentPane().add(nomEmp);
        nomEmp.setBounds(50, 193, 320, 25);

        apEmp.setBorder(null);
        getContentPane().add(apEmp);
        apEmp.setBounds(50, 263, 320, 25);

        contraEmp.setBorder(null);
        getContentPane().add(contraEmp);
        contraEmp.setBounds(50, 338, 320, 25);

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 390, 150, 40);

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 390, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nuevoEmpleado.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            guardarNuevoEmpleado();
        } catch (Exception ex) {
            Logger.getLogger(nuevoEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarNuevoEmpleado() throws Exception{
    
        
        Empleado emp = new Empleado();
        
        int id = Integer.parseInt(idEmp.getText());
        String nom = nomEmp.getText();
        String ap = apEmp.getText();
        String cont = contraEmp.getText();
        String tip = JOptionPane.showInputDialog("ingrese el tipo de usuario que desea: ADMIN o EMPLEADO");
        
        emp.setIdEmpleado(id);
        emp.setNombreEmpleado(nom);
        emp.setApellidoEmpleado(ap);
        emp.setContrasena(cont);
        emp.setTipoEmpleado(tip);
        
        controladorEmpleado.create(emp);
        
        JOptionPane.showMessageDialog(null, "Empleado guardado exitosamente");
    
        idEmp.setText("");
        nomEmp.setText("");
        apEmp.setText("");
        contraEmp.setText("");
        
    }
    
    




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nuevoEmpleado dialog = new nuevoEmpleado(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apEmp;
    private javax.swing.JTextField contraEmp;
    private javax.swing.JTextField idEmp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomEmp;
    // End of variables declaration//GEN-END:variables
}
