/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BD.Consultas;
import Controladores.ProductoJpaController;
import Entidades.Producto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author irisa
 */
public class SeleccionProductoVariasOpciones extends javax.swing.JDialog {

    ProductoJpaController controlProductos = new ProductoJpaController();
    Producto producto;
    String busqueda;
    /**
     * Creates new form SeleccionProductoVariasOpciones
     * @param parent
     * @param modal
     * @param busqueda
     */
    public SeleccionProductoVariasOpciones(javax.swing.JDialog parent, boolean modal, String busqueda) {
        super(parent, modal);
        initComponents();
        System.out.println(busqueda);
        this.busqueda = busqueda;
        CrearModelo();
        Llenar_Tabla();
        this.setSize(600,450);
        this.setLocationRelativeTo(null);
    }
    
    public static DefaultTableModel modelo;
     private void CrearModelo(){
         try {
             modelo = (new DefaultTableModel(
                null, new String [] {
                "id","Nombre",
                "Precio","Codigo de barras","Stock","Proveedor"}){
                Class[] types = new Class [] {
                java.lang.Object.class,
                java.lang.Object.class,
                java.lang.Object.class,
                java.lang.Object.class,
                java.lang.Object.class,
                java.lang.Object.class
                };
                boolean[] canEdit = new boolean [] {
                false,false,false,false,false,false
                };
                @Override
                public Class getColumnClass(int columnIndex) {
                   return types [columnIndex];
                }
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex){
                   return canEdit [colIndex];
                }
            });
          jTable1.setModel(modelo);
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e.toString()+"error");
             e.printStackTrace();
            }    
        }
    private void Llenar_Tabla(){
        try {
            
            Object A[] = null;
            List<Producto>listaProductos;
            listaProductos = controlProductos.findProductoEntities();
            producto= new Consultas().buscarCodigoBarras(busqueda);
            
            
             for (int i = 0; i < listaProductos.size(); i++) {

                 if(listaProductos.get(i).getCodigoBarras().equals(busqueda)){   
              modelo.addRow(A);
              modelo.setValueAt(listaProductos.get(i).getIdProducto(), i, 0);
              modelo.setValueAt(listaProductos.get(i).getNombreProducto(), i, 1);
              modelo.setValueAt(listaProductos.get(i).getPrecioProducto(), i, 2);
              modelo.setValueAt(listaProductos.get(i).getCodigoBarras(), i, 3);
              modelo.setValueAt(listaProductos.get(i).getStock(), i, 4);
              modelo.setValueAt(listaProductos.get(i).getProveedor(), i, 5);
                 }
              
            }
            
           
            /*
            for (int i = 0; i < listaProductos.size(); i++) {

              modelo.addRow(A);
              modelo.setValueAt(listaProductos.get(i).getIdProducto(), i, 0);
              modelo.setValueAt(listaProductos.get(i).getNombreProducto(), i, 1);
              modelo.setValueAt(listaProductos.get(i).getPrecioProducto(), i, 2);
              modelo.setValueAt(listaProductos.get(i).getCodigoBarras(), i, 3);
              modelo.setValueAt(listaProductos.get(i).getStock(), i, 4);
              modelo.setValueAt(listaProductos.get(i).getProveedor(), i, 5);
            }*/
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(33, 33, 510, 327);

        jButton1.setBackground(new java.awt.Color(204, 255, 51));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 380, 138, 42);

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(557, 0, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //boton editar
        Producto prod;
        int sel = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int dato =  (int) model.getValueAt(sel, 0);
        prod = controlProductos.findProducto(dato);
        
        editarProducto ep = new editarProducto(this, false);
        ep.llenarDatos(prod.getIdProducto(), prod.getNombreProducto(), prod.getCodigoBarras(), prod.getPrecioProducto(), prod.getStock());
        ep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionProductoVariasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionProductoVariasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionProductoVariasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionProductoVariasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionProductoVariasOpciones dialog = new SeleccionProductoVariasOpciones(new javax.swing.JDialog(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
